version: "3.5"

services:
  uaitwro:
    build: ./
    network_mode: "host"
    volumes:
    - type: bind
      source: ./docs
      target: /docs
    - type: bind
      source: ./mkdocs.yml
      target: /mkdocs.yml
    command: ["mkdocs", "serve"]