site_name: UA-IT Wroclaw
theme:
  name: material
  palette:
    primary: red

nav:
  - Головна: index.md
  - Авто-мото: automoto.md
  - Готелі і відпочинок: hotels.md
  - Діти: children.md
  - Житло: apartments.md
  - Легалізація: legalisation.md
  - Магазини: shops.md
  - Медицина: healthcare.md
  - Послуги: services.md
  - Ресторани: restaurants.md
  - Розваги: entertainment.md
  - Спорт: sport.md

